### ISSUE TITLE
Specifying an array in sourceDir

### ISSUE THREAD

**Issue by Mauladen** [activeguild/vite-plugin-sass-dts#100]
I ran into a problem when I don't need to generate types for some of my modules in certain folders, at the moment there is no solution how I can do this without specifying folders in src

As an option, it is possible to specify an array of paths, then I, like others, could specify only the necessary folders in src

I also want to say thank you for your work, this plugin has made development more enjoyable for me and my team

**Comment by activeguild** [comment]
Supported in the latest version.
