### ISSUE TITLE
Support sass modern API 

### ISSUE THREAD

**Issue by roman-petrov** [activeguild/vite-plugin-sass-dts#101]
Vite 5.4.0 ships modern sass API support:

* https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#540-beta0-2024-07-30
* https://vitejs.dev/config/shared-options#css-preprocessoroptions

which allows to use [sass pkg: importers](https://sass-lang.com/blog/announcing-pkg-importers/) and has other improvements compared to legacy sass API.

Can this please be supported?

**Comment by activeguild** [comment]
Thank you.
I'm planning on supporting it.

**Comment by roman-petrov** [comment]
That's cool! Thank you for the great plugin!

**Comment by activeguild** [comment]
Supported in the latest version.
