### ISSUE TITLE
`sass` package dependency

### ISSUE THREAD

**Issue by hxhieu** [activeguild/vite-plugin-sass-dts#23]
Hi,

Thanks for the plugin and it works great but my only question is that why'd we be coupled with `sass`?
Some project just pure CSS and don't need any pre-processing and we still need to add `sass` as dependency.
Also according to Vite docs, pre-processing is not recommended [https://vitejs.dev/guide/features.html#css-pre-processors](https://vitejs.dev/guide/features.html#css-pre-processors)

**Comment by activeguild** [comment]
@hxhieu 

Hi, thanks contact.

Of course, in the case of pure css, we don't use the sass package.
In the case of sass file, it converts `sass` to `css` and extracts the class name from it.
The `sass` package is used in a series of steps.

**Comment by activeguild** [comment]
It may be better to change it to dev Dependency according to vite.

**Comment by hxhieu** [comment]
Thanks for your response but I'd think of an "add-on" feature to use `sass`, so core is CSS only but can turn on `sass` (or even `less`). I understand that `sass` is used in between but if there was just an option like `useSass: true/false` then it would be much nicer.

**Comment by activeguild** [comment]
@hxhieu 
I think.

How about prompting install according to `vite`?
https://github.com/vitejs/vite/blob/11409818d934f2b13ba7d5972647d31273fd3293/packages/vite/src/node/plugins/css.ts#L1002

**Comment by activeguild** [comment]
https://github.com/activeguild/vite-plugin-sass-dts/pull/24/files

**Comment by hxhieu** [comment]
Awesome! Thank you
