### ISSUE TITLE
Could it support camelcase option?

### ISSUE THREAD

**Issue by pspgbhu** [activeguild/vite-plugin-sass-dts#25]
In the vite, it support css module camelcase by to set `css.modules.localsConvention: 'camelCase'`.

but this plugin dose not seem to support camelcase option, so could it support camecase option?

**Comment by activeguild** [comment]
@pspgbhu 
Thanks contact.
I think you can change the key to the target setting when 'camelCase' or 'camelCaseOnly' is set in css.modules.global Convention.
Support will take some time.

**Comment by activeguild** [comment]
I think it'll go something like this.
https://github.com/activeguild/vite-plugin-sass-dts/pull/26/commits/081aa66e63200dc079014d85499bf0183e73146f

**Comment by pspgbhu** [comment]
@activeguild thanks, i had review it. and i created a pull request to fixed `toCamelCase` function

**Comment by activeguild** [comment]
@pspgbhu 
Thank you.
I just released it including the PR that I got support for.
