### ISSUE TITLE
less support

### ISSUE THREAD

**Issue by baranwang** [activeguild/vite-plugin-sass-dts#29]
Nice project, don't know if the plugin can support less.

**Comment by activeguild** [comment]
@baranwang 

Thanks contact.

I think less support is possible.It seems that we can support by referring to the following.
It seems that it will take time to respond.
https://github.com/vitejs/vite/blob/6f696be112d5d0c3db433ae9cf0c73af078f2825/packages/vite/src/node/plugins/css.ts#L1164-L1222
