### ISSUE TITLE
Feature request: Only generate for CSS modules

### ISSUE THREAD

**Issue by Munawwar** [activeguild/vite-plugin-sass-dts#36]
First thing - this is a very cool plugin! Thanks

Currently this plugin generates the types for all css files. How about generating it *only* for css module file (any file name ending with .module.(css|scss|sass) file names). Why? Because type check is mostly useful for those files as they are imported and used in JS. (Question: Is it even possible to type check usage of css classes of non-module css files?)

Second feature request is that generation be done only on development mode, so it doesn't slow down a production build.

Tell me if you agree, I can make a pull request. If you need feature flags for both features mention it.

**Comment by activeguild** [comment]
@Munawwar 

Thanks contact.

>Currently this plugin generates the types for all css files. How about generating it only for css module file (any file name ending with .module.(css|scss|sass) file names). Why?

That looks good.
As with `vite`, it seems a good idea to avoid checking with regular expressions.
https://github.com/vitejs/vite/blob/6f696be112d5d0c3db433ae9cf0c73af078f2825/packages/vite/src/node/plugins/css.ts#L87

>Second feature request is that generation be done only on development mode, so it doesn't slow down a production build.

How about adding `enabled_mode` to the configuration file to check only enabled modes?
```
enabled_mode: ['development', 'production']
```

**Comment by Munawwar** [comment]
> As with vite, it seems a good idea to avoid checking with regular expressions.
What  do you suggest? string split by dot? I can run a benchmark on which is faster.
(by the way that link you pasted is to vite's code and they continue to use RegExp?)

> How about adding enabled_mode to the configuration file to check only enabled modes?
And what do you suggest the default config should be? Both?

**Comment by activeguild** [comment]
>What do you suggest? string split by dot? I can run a benchmark on which is faster.
(by the way that link you pasted is to vite's code and they continue to use RegExp?)

Add the following code to `util.ts`.
```
export const cssModuleReg = new RegExp(`\\.module${cssLangs}`)
export const isCSSModuleRequest = (request: string): boolean =>
  cssModuleReg.test(request)
```
And how about a change to convert `isCssRequest` in `index.ts ` to `isCSSModuleRequest`?

>And what do you suggest the default config should be? Both?

Defaults should be as follows.
```
nabled_mode: ['development']
```

**Comment by Munawwar** [comment]
Ok. Will go with camel case `enabledMode` as other options like `allGenerate` is already camel case.

By the way, this makes `allGenerate` obsolete. You can now disable generation by using `enabledMode: []`

**Comment by activeguild** [comment]
That's a very good point of view.
I don't need `allGenerate` anymore.
