### ISSUE TITLE
Adding sass as a peer dependency?

### ISSUE THREAD

**Issue by nksfrank** [activeguild/vite-plugin-sass-dts#49]
looking through the project while trying to determine if it's possible to use this package for pure `.css` files I saw what looks to me like `sass` is required: https://github.com/activeguild/vite-plugin-sass-dts/blob/8456f52921c35d723a24888314059b1b97df59e0/src/css.ts#L86

Should this project add `peerDependencies.sass: *` to let anyone using this know that `sass` is required when installing the package with a package manager?

**Comment by activeguild** [comment]
@nksfrank 
Hi, Thanks contact.
Yes, it is. We think it is best to specify `peerDependencies.sass: *`.

**Comment by activeguild** [comment]
Fixed and latest version is now available.
