### ISSUE TITLE
Attempt to use in a vite project throws error

### ISSUE THREAD

**Issue by jhechtf** [activeguild/vite-plugin-sass-dts#54]
Attempting to add this to a vite project that uses a `vite.config.ts` file throws this error

```
import { resolveConfig } from "prettier";
         ^^^^^^^^^^^^^
SyntaxError: Named export 'resolveConfig' not found. The requested module 'prettier' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

Project is a brand-new SCSS project and does not have anything other than the svelte plugin running.

**Comment by activeguild** [comment]
@jhechtf 

Thanks for the contact.
Confirmation.

**Comment by activeguild** [comment]
@jhechtf 

I've fixed it and released the latest version.
Please check it out.

**Comment by jhechtf** [comment]
well it no longer errors, but I also don't think it's working as expected.

This is at the top of the file

```
import globalClassNames, {
  ClassNames as GlobalClassNames,
} from "file:C:UsersJimprojectsgit-better\better-ui\vite.config.tsstyles.d.ts";
```

**Comment by activeguild** [comment]
Can you provide a sample of the issue that will be generated?

**Comment by jhechtf** [comment]
Apologies but I've given the header of the output. The class names were
correct but that import path is very clearly incorrect.

The slashes before the file name are all removed, and it's trying to find a
filename called "vite.config.tsstyles.d.ts". If I can ill see about fixing
the issue in a pr when I get home but I'm currently not near a computer.

**Comment by activeguild** [comment]
OK, I'm waiting for the PR.

**Comment by jhechtf** [comment]
NVM this seems to be user error. out of habit I used `import.meta.url` instead of `__dirname`

**Comment by activeguild** [comment]
Are there any other issues left?

**Comment by jhechtf** [comment]
Nope. Think we're good. Closing.
