### ISSUE TITLE
vite-plugin-sass-dts wont generate typescript definitions for `resolve.alias` paths. 

### ISSUE THREAD

**Issue by typhoeus-ltd** [activeguild/vite-plugin-sass-dts#57]
title ^

repro: [here](https://github.com/typhoeus-ltd/vite-plugin-sass-dts-repro)

edit: Also I'm getting a bunch of code log? errors prettier related?
```
SyntaxError: Type expected. (4:25)
  2 | };
  3 | export default classNames;
> 4 | export type ClassNames =
```
something like
![image](https://user-images.githubusercontent.com/90290584/183547321-9f2b0709-0dd9-45f3-90c4-3351213909ef.png)

I'm not sure what it is but I can't push my repo publicly, it's proprietary stuff, just I can tell my code isn't wrong, it builds successfully without the plugin.

**Comment by activeguild** [comment]
@typhoeus-ltd 
Hi! Thanks for the detailed info.
I'll check it out in a minute.

**Comment by activeguild** [comment]
It worked fine in my environment.
There may be differences between windows and mac.
I don't have a windows machine so it is difficult to verify, can I get some more error details?

**Comment by activeguild** [comment]
@typhoeus-ltd 
You may have an old prettier installed on global and it may be causing the error. Can you check by installing the latest prettier?
