### ISSUE TITLE
Named imports

### ISSUE THREAD

**Issue by tomahl** [activeguild/vite-plugin-sass-dts#60]
Hi there,

As a user I would like to use named imports to keep my classNames shorter and more readable.

```typescript
import { foo, bar } from "./my.module.scss";

<div className={foo}>
    <div className={bar}></div>
</div>
```
Maybe I have missed something, but I was not able to make it work with the current version.

Thanks for your great work. 👍

**Comment by activeguild** [comment]
@tomahl 

Should be fixed in with!

```
"vite-plugin-sass-dts": "^1.2.4"
```

Thanks for the issue!!

**Comment by tomahl** [comment]
You're awesome, thanks for the fast fix. 👍
