### ISSUE TITLE
Exports based on filename

### ISSUE THREAD

**Issue by tomahl** [activeguild/vite-plugin-sass-dts#62]
Hi again.

Currently, all exports use the same name `const classNames` and `type ClassNames` which Imo makes imports via autocompletion less readable. It would have been great if there was a choice where these names were based on the fileName instead. So my file `colors.scss` would export something like `const colors: {}` and `type ColorNames or ColorKeys` etc.

Keep up the good work.

**Comment by activeguild** [comment]
I think.

It might be a good idea to provide an option like 'replacement' 
so that the variable to be output can be replaced.

**Comment by activeguild** [comment]
@tomahl 

Should be fixed in with!

```
"vite-plugin-sass-dts": "^1.2.6"
```

Thanks for the issue!!
