### ISSUE TITLE
Relax node engine version

### ISSUE THREAD

**Issue by tmair** [activeguild/vite-plugin-sass-dts#68]
The node engine version in `package.json` is set to `18.12.1`. This seems overly permissive, as we would like to upgrade the node version to a higher version.

Could we relax the version to `>= 18.12.1`?

**Comment by activeguild** [comment]
@tmair 

Oops!
Modify to match the node version of vite.

**Comment by activeguild** [comment]
@tmair 

Should be fixed in with!
```
"vite-plugin-sass-dts": "^1.2.12"
```
Thanks for the issue!!

https://github.com/activeguild/vite-plugin-sass-dts/blob/9b4dd2645e68d639394e23c7b43f709abfd47f73/package.json#L4-L6
