### ISSUE TITLE
README does not describe the latest specification

### ISSUE THREAD

**Issue by wand2016** [activeguild/vite-plugin-sass-dts#69]
https://github.com/activeguild/vite-plugin-sass-dts/blob/9b4dd2645e68d639394e23c7b43f709abfd47f73/README.md?plain=1#L141

https://github.com/activeguild/vite-plugin-sass-dts/commit/ee6d79df9554341bb2665db355f89ae7f435b2f7

The type `ClassNames` is no longer outputted in v1.2.12.

**Comment by activeguild** [comment]
@wand2016 

Thank you!
Should be fixed in with!

```
"vite-plugin-sass-dts": "^1.2.13"
```
