### ISSUE TITLE
Link with query string is recognized as a real file, resulting in a failure to open the file.

### ISSUE THREAD

**Issue by x6ax6b** [activeguild/vite-plugin-sass-dts#74]
I don't have any problems in development mode, but I just wanted to let you know that this error can happen in some cases.

```
[Error: ENOENT: no such file or directory, open '/Users/x6ax6b/dev/src/Component.module.scss?direct'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/x6ax6b/dev/src/Component.module.scss?direct'
}
```

I'm using it with 'vite-plugin-ssr' and this plugin seems to automatically attach query strings to style links in development mode.

**Comment by activeguild** [comment]
@x6ax6b 

Thank you. We have responded and released the following version.
```
vite-plugin-sass-dts: 1.3.4
```
