### ISSUE TITLE
Unnecessary properties are created.

### ISSUE THREAD

**Issue by x6ax6b** [activeguild/vite-plugin-sass-dts#75]
When using with tailwindcss, if a class has a decimal point, the generated type has an unnecessary property.

source:
```
.test {
  @apply px-1.5;
}
```

d.ts:
```
declare const classNames: {
  readonly test: 'test';
  readonly '5': '5';
};
export = classNames;
```

**Comment by activeguild** [comment]
@x6ax6b 

Thank you. We have responded and released the following version.
```
vite-plugin-sass-dts: 1.3.4
```
