### ISSUE TITLE
Usage with Nuxt?

### ISSUE THREAD

**Issue by aa-ndrej** [activeguild/vite-plugin-sass-dts#78]
I am trying to use this package in a Nuxt project.
The type generation and autocompleting etc. is working flawlessly. 🚀

However while developing I am getting a lot of error messages in the console, like the following:
```shell
ERROR  ENOENT: no such file or directory, open '/.../src/pages/index.vue?vue&type=style&index=0&lang.module.scss'
...
``` 

My `nuxt.config.ts` looks like this:
```typescript
import viteSassDts from 'vite-plugin-sass-dts'

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  srcDir: 'src',

  vite: {
    plugins: [
      viteSassDts(),
    ],
  },
})
```

Do I need to configure something else for the error messages to disapear?

**Comment by activeguild** [comment]
@aa-ndrej 
We have confirmed that it works fine in the latest nuxt environment.
Here is a sample
https://github.com/activeguild/vite-plugin-sass-dts/tree/master/example/nuxt-sass

Can you provide the repository where the event occurs, etc.?

**Comment by aa-ndrej** [comment]
@activeguild I tried reproducing the errors in the example repo. The error logs occur whenever I have a `.vue` file where there is an CSS import in the `script` part AND additionally there is a `<style module lang="scss"> ... </style>` part.

So if you e.g. change the `app.vue` file in the example to:
```vue
<template>
  <div>
    <div :class="$style.bar" />
    <NuxtWelcome />
  </div>
</template>

<script setup>
import styles from './app.module.scss'
console.log('styles :>> ', styles)
</script>

<style module lang="scss">
.bar {
  background-color: #dcfbec;
  height: 50px;
}
</style>
```
The errors only occur when the `style` tag includes the `module` modifier.

I use it like that because I am outsourcing common styles into seperate CSS modules but have the component or page specific styles in the vue file itself.
Function wise everything is working as expected though and when I build the project and run the generated files there are no error messages.

The error logs just appear when running `pnpm run dev`. So it is not a major problem but just a bit annoying :D
When deactivating the plugin the error messages disapear, so I would not say that it is a nuxt issue.

Btw thank you for this little helper 🙏🏼 Just discovered it yesterday and really enjoy it so far!

**Comment by activeguild** [comment]
@aa-ndrej 

The latest version has been released with fixes for build errors.
Thank you for the issue report.

**Comment by aa-ndrej** [comment]
Thank you! Amazing work :)
