### ISSUE TITLE
Custom outputFilePath cause auto import style.d error

### ISSUE THREAD

**Issue by truongnat** [activeguild/vite-plugin-sass-dts#82]
Hi @activeguild,

Have good day <3,

I meet issue when using this library,  i want custom outputFilePath from './src/style.d.ts' to './src/@types/style.d.ts'.

Because i move all file .d.ts to folder src/@types.

but custom above will error import when generate.

![Screenshot 2023-07-28 at 00 19 18](https://github.com/activeguild/vite-plugin-sass-dts/assets/87919564/0a937872-6a8e-4619-add1-a91f44437322)
![Screenshot 2023-07-28 at 00 19 28](https://github.com/activeguild/vite-plugin-sass-dts/assets/87919564/90aebc12-33f7-43f6-8bdb-ebf075b39b0b)
![Screenshot 2023-07-28 at 00 20 22](https://github.com/activeguild/vite-plugin-sass-dts/assets/87919564/97ed4bad-8bfc-4bc4-a371-156ea46ca5e4)

i want change to:

![Screenshot 2023-07-28 at 00 20 42](https://github.com/activeguild/vite-plugin-sass-dts/assets/87919564/b9861816-4315-449c-b5e0-42af603ba272)

Thanks <3

**Comment by truongnat** [comment]
i found function `getRelativePath`, this function return relative path, but when `to` path includes @types or another folderm it still return `../..`

```javascript
export const getRelativePath = (
  from: string | undefined,
  to: string | undefined
) => {
  const relativePath =
    path.relative(path.dirname(from || ''), path.dirname(to || '')) || './'

  return relativePath.endsWith('..') ? `${relativePath}/` : relativePath
}
```

**Comment by activeguild** [comment]
@truongnat 

Revised and published.
Please check it.

**Comment by truongnat** [comment]
> @truongnat
> 
> Revised and published. Please check it.

OKay thakns <
