### ISSUE TITLE
Add option to use double quote

### ISSUE THREAD

**Issue by bryanjtc** [activeguild/vite-plugin-sass-dts#84]
My project uses prettier settings with double quote. It throws errors when d.ts files are generated. I prefer using a double quote option instead of ignoring the files with prettier ignore

**Comment by activeguild** [comment]
@bryanjtc 

Thank you.

I know there are many ways to do this, but are there any best practices?
For example, tell them where to find the project's pritter configuration file.

**Comment by activeguild** [comment]
@bryanjtc 

Allow optional prettierFilePath to be specified. This has been reflected in the latest release.
