### ISSUE TITLE
@extend %placeholder results in empty declaration file

### ISSUE THREAD

**Issue by erikbrgn** [activeguild/vite-plugin-sass-dts#86]
Hello! Thanks for this very useful plugin.

I've found an issue where extending classes/placeholders from other files results in an "empty" declaration file being generated.

Perhaps this goes against the idea of module files, but a very simple example to illustrate the issue:

```css
.foo {
  background-color: blue;
}
```
Works fine when imported, and a declaration file is generated containing `readonly foo: 'foo'`

But, doing this results in a file only containing `declare const classNames: {}`:

```css
@use '@style/placeholders';

.foo {
  @extend %bar;
}
```
I've narrowed it down to being an issue with the `@use '@style/placeholders' ;` specifically, because using a placeholder defined in the same file works as expected.

**Comment by activeguild** [comment]
@erikbrgn 

I could not reproduce it in my environment. 
Can you provide a minimum repository where I can verify the event?

**Comment by activeguild** [comment]
@erikbrgn 

I solved this by adding `module` to the file name.
https://github.com/activeguild/sass-dts-issue/commit/9dee0915df71e3434581fb050ab1605ee064d64a

Was this a separate issue from this issue?

**Comment by erikbrgn** [comment]
> @erikbrgn
> 
> I solved this by adding `module` to the file name. [activeguild/sass-dts-issue@9dee091](https://github.com/activeguild/sass-dts-issue/commit/9dee0915df71e3434581fb050ab1605ee064d64a)
> 
> Was this a separate issue from this issue?

No, that wasn't the issue, it works as expected (according to your docs). 

The issue I recreated is that the generated `scss` declaration file for the `button` component is empty, but it shouldn't be. If you remove one of the lines (There's a comment about it) in the `index.module.scss` file, a proper declaration file is generated as expected.

So, the issue is in the `components/button` directory, rather than the `scss` directory.

**Comment by erikbrgn** [comment]
@activeguild Huh, interesting. You're right, it solves the problem. Thanks for looking into it.

I'll close this issue.
