### ISSUE TITLE
Update peer dependency to vite 5

### ISSUE THREAD

**Issue by MarionHauffNAV** [activeguild/vite-plugin-sass-dts#87]
vite-plugin-sass-dts has peer dependency to vite ^3 or ^4.
This results in the following error message if trying to upgrade to vite 5:

```
Could not resolve dependency:
npm WARN peer vite@"^3 || ^4" from vite-plugin-sass-dts@1.3.11
```

**Comment by activeguild** [comment]
@MarionHauffNAV 

Thanks!!
Fixed and released.
