### ISSUE TITLE
Option for running on files not included in the bundle

### ISSUE THREAD

**Issue by MrGVSV** [activeguild/vite-plugin-sass-dts#88]
It would be nice if this plugin were able to run on non-bundled files as well. 

While developing, it's pretty common to not have everything exported (and thus, not included in the bundle) right away. Because of this, it's easy to run into type errors since the `d.ts` files don't generate for those modules. I think an option to allow the plugin to run on _all_ SCSS module files could be very useful in these situations.

Note: I'm a bundler noob lol so there may be an option or configuration step I'm missing to achieve this.

**Comment by activeguild** [comment]
@MrGVSV 

Thanks.
Fixed and released.
