### ISSUE TITLE
Building the example fails

### ISSUE THREAD

**Issue by iPapatsoris** [activeguild/vite-plugin-sass-dts#93]
Hi,

By running `yarn build` in `/example/react-sass` on master branch, I get

> Error: Unexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
> (vite:css) transform "vite-plugin-sass-dts-master/example/react-sass/src/App.module.scss"
>     at process.handleBeforeExit (file:///vite-plugin-sass-dts-master/example/react-sass/node_modules/rollup/dist/es/shared/node-entry.js:19948:28)
>     at Object.onceWrapper (node:events:628:26)
>     at process.emit (node:events:513:28)

Dev mode doesn't seem to work either, when loading the page it looks like it's stuck in a loop.

**Comment by activeguild** [comment]
@iPapatsoris 

Hi!!

Fixed `/example/react-sass` to get the build to pass.
Check it out.
