### ISSUE TITLE
Importing an scss file that uses the common namespace results in error

### ISSUE THREAD

**Issue by iPapatsoris** [activeguild/vite-plugin-sass-dts#96]
In the `react-sass` example, if I add the line `@use '../App.module.scss';` on `User.module.scss`, I receive 

> Error: There is no module with the namespace "common".
>   ╷
> 8 │   background-color: common.$primary;
>   │                     ^^^^^^^^^^^^^^^
>   ╵
>   src/App.module.scss 8:21        @use
>   src/User/User.module.scss 1:27  root stylesheet

**Comment by activeguild** [comment]
@iPapatsoris 

This is an error because User.module.scss is interpreted and transpiled as follows, which is beyond the scope of this plugin because it is a sass error.
I thought it would be a good idea to review the file dependencies.
```
@use '@/styles' as common;
@use '../App.module.scss';

.name {
  line-height: 1;
}
```

**Comment by iPapatsoris** [comment]
Ah yes, you are right. I wasn't aware that it was a native SASS error. Thanks for the help!
